env: dev # dev、test、prod、local

server:
  name: moon-palace
  metadata:
    description: palace是moon监控系列的监控平台，用于管理告警、监控、配置、日志、数据源等
    background: 寓意为月宫，表示moon系列的统一管理平台
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
#  registry:
#    type: "etcd"
#    etcd:
#      endpoints:
#        - 127.0.0.1:20000
#      username: ""
#      password: ""
#      timeout: 10s
  jwt:
    sign_key: "moon-sign_key"
    issuer: "moon-palace"
    white_list:
      - /api.admin.authorization.Authorization/Login
      - /api.admin.authorization.Authorization/Captcha
      - /api.admin.authorization.Authorization/CreatePassword
      - /api.Health/Check

    # 角色权限白名单, 包含white_list， 因为不需要登录的接口自然也不需要RBAC
    rbac_white_list:
#      - /api.admin.authorization.Authorization/Login
#      - /api.admin.authorization.Authorization/Captcha
#      - /api.admin.authorization.Authorization/CreatePassword

data:
  database:
    driver: "mysql"
    dsn: "root:12345678@tcp(127.0.0.1:3306)/moon?charset=utf8mb4&parseTime=True&loc=Local"
  bizDatabase:
    driver: "mysql"
    dsn: "root:12345678@tcp(127.0.0.1:3306)/"
  cache:
    redis:
      network: "tcp"
      addr: 127.0.0.1:6379
      db: 0
      password: ""
      read_timeout: 0.2s
      write_timeout: 0.2s
      dial_timeout: 0.2s
    nutsDB:
      path: ./tmp/nutsdb
      bucket: test

micro_server:
  discovery:
    etcd:
      endpoints:
        - 127.0.0.1:2379
      token: ""
      timeout: 10s
  rabbit_server:
    endpoint: "127.0.0.1:9001"
    timeout: 2s
    token: ""