env: dev
server:
  name: "Palace"
  metadata:
    description: palace是moon监控系列的监控平台，用于管理告警、监控、配置、日志、数据源等
    background: 寓意为月宫，表示moon系列的统一管理平台

http:
  addr: 0.0.0.0:8000
  timeout: 50s

grpc:
  addr: 0.0.0.0:9000
  timeout: 50s

jwt:
  sign_key: "moon-sign_key"
  issuer: "moon-palace"
  expire: 3600s

  allow_list:
    - /api.admin.authorization.Authorization/Login
    - /api.admin.authorization.Authorization/Captcha
    - /api.admin.authorization.Authorization/CreatePassword
    - /api.Health/Check
    - /api.Alert/Hook
    - /api.admin.authorization.Authorization/VerifyEmail
    - /api.admin.authorization.Authorization/SetEmailWithLogin

cache:
  driver: "free"
  redis:
    network: "tcp"
    addr: localhost:6379
    db: 0
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 0.2s
  nutsDB:
    path: ./tmp/nutsdb
    bucket: test
  free:
    size: 0

#tracer:
#  driver: "jaeger"
#  jaeger:
#    endpoint: "http://localhost:14268/api/traces"

#discovery:
#  driver: "etcd"
#  etcd:
#    endpoints:
#      - localhost:20000
#      - localhost:20002
#      - localhost:20004
#    username: ""
#    password: ""
#    timeout: 50s

micro_server:
  rabbit_server:
    network: "rpc"
    nodeVersion: ""
#    endpoint: "discovery:///moon_rabbit"
    endpoint: "127.0.0.1:9002"
    timeout: 50s
    secret: ""
  hou_yi_server:
    network: "rpc"
    nodeVersion: ""
#    endpoint: "discovery:///moon_houyi"
    endpoint: "127.0.0.1:9001"
    timeout: 50s
    secret: ""
#  hou_yi_servers:
#    - network: "rpc"
#      nodeVersion: ""
#      endpoint: "discovery:///moon_houyi_1"
#      timeout: 50s
#      secret: ""
#    - network: "rpc"
#      nodeVersion: ""
#      endpoint: "discovery:///moon_houyi_2"
#      timeout: 50s
#      secret: ""

database:
  driver: "mysql"
  debug: true
  dsn: "root:12345678@tcp(localhost:3306)/moon?charset=utf8mb4&parseTime=True&loc=Local"
#  driver: "sqlite"
#  debug: true
#  dsn: "main.db"
bizDatabase:
  driver: "mysql"
  debug: false
  dsn: "root:12345678@tcp(localhost:3306)/"
#  driver: "sqlite"
#  debug: true
alarmDatabase:
  driver: "mysql"
  debug: false
  dsn: "root:12345678@tcp(localhost:3306)/"
#  driver: "sqlite"
#  debug: false

#oauth2:
#  redirect_uri: "http://127.0.0.1:5173/"
#  github:
#    client_id: ""
#    client_secret: ""
#    callback_uri: "http://localhost:8000/auth/github/callback"
#    scopes:
#      - "user"
#      - "email"
#  gitee:
#    client_id: ""
#    client_secret: ""
#    callback_uri: "http://localhost:8000/auth/gitee/callback"
#    scopes:
#      - "user_info"
#      - "emails"
#
#email_config:
#  host: smtp.163.com
#  port: 25
#  user:
#  pass: