env: dev # dev、test、prod、local

server:
  name: moon_rabbit
  metadata:
    description: 是moon监控系列的消息组件，可以独立部署，接受任意的hook消息，并支持邮件、钉钉、企业微信、飞书等告警
    background: 寓意为月宫中的玉兔，专门用于消息通知
  http:
    addr: 0.0.0.0:8001
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 2s
  registry:
    type: "etcd"
    etcd:
      endpoints:
        - 127.0.0.1:20000
        - 127.0.0.1:20002
        - 127.0.0.1:20004
      username: ""
      password: ""
      timeout: 10s
data:
  cache:
#    redis:
#      network: "tcp"
#      addr: 127.0.0.1:6379
#      db: 0
#      password: ""
#      read_timeout: 0.2s
#      write_timeout: 0.2s
#      dial_timeout: 0.2s
    nutsDB:
      path: ./tmp/nutsdb
      bucket: test

templates:
  email: |
    <h1>{{.Title}}</h1>
    <p>{{.Content}}</p>
  dingTalk: |
    {
      "at": {
          "atUserIds":[
              "014728255240768602"
          ],
          "isAtAll": {{.IsAtAll}}
      },
      "text": {
          "content":"我就是我, {{.Content}}"
      },
      "msgtype":"text"
    }

global_email_config:
  host: smtp.163.com
  port: 25
  user:
  pass:

receivers:
  test:
    emails:
      - to: "1058165620@qq.com"
        subject: "Moon监控测试告警"
        content: ""
        template: "email"
        contentType: "text/plain"
        cc:
        attachUrl:
#    hooks:
#      - dingTalk:
#          webhook: "https://oapi.dingtalk.com/robot/send?access_token="
#          secret: ""
#          content: ""
#          template: "dingTalk"