env: dev # dev、test、prod、local

dependPalace: true
server:
  name: moon_rabbit
  httpEndpoint: "127.0.0.1:8002"
  grpcEndpoint: "127.0.0.1:9002"
  network: "rpc"
  secret: ""
  metadata:
    description: 是moon监控系列的消息组件，可以独立部署，接受任意的hook消息，并支持邮件、钉钉、企业微信、飞书等告警
    background: 寓意为月宫中的玉兔，专门用于消息通知

http:
  addr: 0.0.0.0:8002
  timeout: 2s
grpc:
  addr: 0.0.0.0:9002
  timeout: 2s
data:
  cache:
    driver: "free"
    redis:
      network: "tcp"
      addr: 127.0.0.1:6379
      db: 0
      password: ""
      read_timeout: 0.2s
      write_timeout: 0.2s
      dial_timeout: 0.2s
    nutsDB:
      path: ./tmp/nutsdb
      bucket: test
    free:
      size: 10485760

# TODO 调整模板结构， 支持多租户
templates:
  email: |
    <h1>监控告警</h1>
    <p>{{ . }}</p>
  dingtalk: |
    {
       "msgtype": "markdown",
       "markdown": {
           "title":"Moon监控告警通知",
           "text": "#### Moon监控告警通知\n\n >摘要：{{ .annotations.summary}}\n\n >内容：{{ .annotations.description }}\n\n >告警时间：{{ .startsAt }}\n"
       }
    }
  feishu: |
    {
        "msg_type": "post",
        "content": {
            "post": {
                "zh_cn": {
                    "title": "Moon监控告警通知",
                    "content": [
                        [{
                            "tag": "text",
                            "text": "摘要：{{ .annotations.summary}}"
                        }],
                        [{
                            "tag": "text",
                            "text": "内容：{{ .annotations.description }}"
                        }],
                        [{
                            "tag": "text",
                            "text": "告警时间：{{ .startsAt }}"
                        }]
                    ]
                }
            }
        }
    }

  wechat: |
    {
        "msgtype": "markdown",
        "markdown": {
            "content": "Moon监控告警，请相关同事注意。\n
             >摘要:<font color=\"comment\">{{ .annotations.summary}}</font>
             >内容:<font color=\"comment\">{{ .annotations.description }}</font>
             >告警时间:<font color=\"comment\">{{ .startsAt }}</font>"
        }
    }


global_email_config:
  host: smtp.163.com
  port: 25
  user:
  pass:

receivers:
  test:
    emails:
      - to: "1058165620@qq.com"
        subject: "Moon监控测试告警"
        content: ""
        template: "email"
        contentType: "text/plain"
        cc:
        attachUrl:
#    hooks:
#      - dingTalk:
#          webhook: "https://oapi.dingtalk.com/robot/send?access_token="
#          secret: ""
#          content: ""
#          template: "dingTalk"

#discovery:
#  driver: "etcd"
#  etcd:
#    endpoints:
#      - 127.0.0.1:20000
#      - 127.0.0.1:20002
#      - 127.0.0.1:20004
#    username: ""
#    password: ""
#    timeout: 10s

palace_server:
  network: "rpc"
  nodeVersion: ""
  #  endpoint: "discovery:///moon_palace"
  endpoint: "127.0.0.1:9000"
  timeout: 50s
  secret: ""