version: "3.8"
services:
  palace:
    image: aidemoonio/palace:latest
    container_name: moon_palace
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./cmd/server/palace/configs:/data/conf

  houyi:
    image: aidemoonio/houyi:latest
    container_name: moon_houyi
    ports:
      - "8001:8000"
      - "9001:9000"
    volumes:
      - ./cmd/server/houyi/configs:/data/conf