version: "3.8"
services:
  palace:
    image:  docker.cloudimages.asia/aidemoonio/palace:latest
    container_name: moon_palace
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./palace:/data/conf

  houyi:
    image:  docker.cloudimages.asia/aidemoonio/houyi:latest
    container_name: moon_houyi
    ports:
      - "8001:8001"
      - "9001:9001"
    volumes:
      - ./houyi:/data/conf

  rabbit:
    image: docker.cloudimages.asia/aidemoonio/rabbit:latest
    container_name: moon_rabbit
    ports:
      - "8002:8002"
      - "9002:9002"
    volumes:
      - ./rabbit:/data/conf

  # 如需使用域名，请将web和palace解析到统一域名下，/api解析到palace
  web:
    image: docker.cloudimages.asia/aidemoonio/moon-frontend:latest
    container_name: web
    ports:
      - "5173:80"