env: dev # dev、test、prod、local

server:
  name: moon_houyi
  metadata:
    description: 是moon监控系列的告警组件，可以独立部署，接受prom类型规则，也可以接受alertmanager类型组件的告警推送
    background: 寓意为天神后羿，专门用于监控规则告警事件
http:
  addr: 0.0.0.0:8001
  timeout: 50s
grpc:
  addr: 0.0.0.0:9001
  timeout: 50s

cache:
  driver: "free"
  redis:
    network: "tcp"
    addr: 192.168.7.76:6379
    db: 0
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 0.2s
  nutsDB:
    path: ./tmp/nutsdb
    bucket: test
  free:
    size: 10485760

watch:
  strategy:
    timeout: 10s
    interval: "@every 10s"
  alertEvent:
    timeout: 10s
    interval: 10s

#discovery:
#  driver: "etcd"
#  etcd:
#    endpoints:
#      - localhost:20000
#      - localhost:20002
#      - localhost:20004
#    username: ""
#    password: ""
#    timeout: 50s

rabbit_server:
  network: "rpc"
  nodeVersion: ""
#  endpoint: "discovery:///moon_rabbit"
  endpoint: "discovery:///moon_rabbit"
  timeout: 50s
  secret: ""
palace_server:
  network: "rpc"
  nodeVersion: ""
#  endpoint: "discovery:///moon_palace"
  endpoint: "127.0.0.1:9000"
  timeout: 50s
  secret: ""